import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { categories, products } from './schema';
import { createId } from '@paralleldrive/cuid2';

const client = createClient({ url: 'file:./db.sqlite' });
const db = drizzle(client);

async function seed() {
  const cats = [
    {
      id: createId(),
      slug: 'power-inverter',
      name: '순수 정현파 인버터',
      nameEn: 'Pure Sine Wave Inverter',
      sortOrder: 1,
    },
    {
      id: createId(),
      slug: 'lcd-inverter',
      name: '탈착형 LCD 인버터',
      nameEn: 'Detachable LCD Inverter',
      sortOrder: 2,
    },
    {
      id: createId(),
      slug: 'ups-inverter',
      name: 'UPS 인버터 충전기',
      nameEn: 'UPS Inverter Charger',
      sortOrder: 3,
    },
    {
      id: createId(),
      slug: 'hybrid-inverter',
      name: '하이브리드 인버터',
      nameEn: 'Hybrid Inverter',
      sortOrder: 4,
    },
    {
      id: createId(),
      slug: 'inverter-pcba',
      name: '인버터 PCBA',
      nameEn: 'Inverter PCBA',
      sortOrder: 5,
    },
    {
      id: createId(),
      slug: 'ups-pcba',
      name: 'UPS 인버터 PCBA',
      nameEn: 'UPS Inverter PCBA',
      sortOrder: 6,
    },
    {
      id: createId(),
      slug: 'micro-inverter',
      name: '마이크로 인버터',
      nameEn: 'Micro Inverter',
      sortOrder: 7,
    },
  ];

  await db.insert(categories).values(cats).onConflictDoNothing();
  console.log('Categories seeded:', cats.length);

  const catMap = Object.fromEntries(cats.map((c) => [c.slug, c.id]));

  const prods = [
    // 1. 순수 정현파 인버터 (8)
    {
      id: createId(),
      slug: 'gy-e500',
      name: '500W 순수 정현파 인버터',
      nameEn: '500W Pure Sine Wave Inverter',
      modelNo: 'GY-E500',
      categoryId: catMap['power-inverter']!,
      description:
        '500W 소형 순정사인파 인버터. 듀얼 USB(QC18W + PD30W) 포트 내장. 캠핑, 차량, 소형 전자기기에 최적.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181420230112465.jpg',
      specInputVoltage: 'DC 12V/24V 자동감지',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '500W',
      specFormFactor: '컴팩트형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        '듀얼 USB (QC18W+PD30W)',
        'THD < 3%',
        '종합 보호 기능',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 1,
    },
    {
      id: createId(),
      slug: 'gy-e1000',
      name: '1000W 순수 정현파 인버터',
      nameEn: '1000W Pure Sine Wave Inverter',
      modelNo: 'GY-E1000',
      categoryId: catMap['power-inverter']!,
      description:
        '1000W 순정사인파 인버터. LCD 디스플레이, 유선 리모컨, 듀얼 USB 포트 내장. 캠핑, 차량, 비상전원에 최적.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181420230112465.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '유선 리모컨',
        '듀얼 USB 포트',
        '과부하 보호',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 2,
    },
    {
      id: createId(),
      slug: 'gy-e1500',
      name: '1500W 순수 정현파 인버터',
      nameEn: '1500W Pure Sine Wave Inverter',
      modelNo: 'GY-E1500',
      categoryId: catMap['power-inverter']!,
      description:
        '1500W 순정사인파 인버터. LCD 디스플레이, 무선 리모컨. 높은 서지 전력으로 모터 기기 구동 가능.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181420230112465.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1500W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '고서지 전력',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 3,
    },
    {
      id: createId(),
      slug: 'gy-e2000',
      name: '2000W 순수 정현파 인버터',
      nameEn: '2000W Pure Sine Wave Inverter',
      modelNo: 'GY-E2000',
      categoryId: catMap['power-inverter']!,
      description:
        '2000W 대용량 순정사인파 인버터. 가전기기 및 전공구 구동에 적합. 스마트 냉각팬 탑재.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181349480128617.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '2000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '스마트 냉각팬',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 4,
    },
    {
      id: createId(),
      slug: 'gy-e3000',
      name: '3000W 순수 정현파 인버터',
      nameEn: '3000W Pure Sine Wave Inverter',
      modelNo: 'GY-E3000',
      categoryId: catMap['power-inverter']!,
      description:
        '3000W 고출력 순정사인파 인버터. 산업용 및 대형 가전기기 구동에 최적화.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181349480128617.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '3000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '종합 보호 기능',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 5,
    },
    {
      id: createId(),
      slug: 'gy-e4000',
      name: '4000W 순수 정현파 인버터',
      nameEn: '4000W Pure Sine Wave Inverter',
      modelNo: 'GY-E4000',
      categoryId: catMap['power-inverter']!,
      description:
        '4000W 고출력 순정사인파 인버터. 소프트 스타트 기능으로 기기 보호. 스마트 냉각 시스템.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181145520128414.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '4000W',
      specFormFactor: '대형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '스마트 냉각팬',
        '소프트 스타트',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 6,
    },
    {
      id: createId(),
      slug: 'gy-e5000',
      name: '5000W 순수 정현파 인버터',
      nameEn: '5000W Pure Sine Wave Inverter',
      modelNo: 'GY-E5000',
      categoryId: catMap['power-inverter']!,
      description:
        '5000W 고출력 순정사인파 인버터. 고효율 설계로 장시간 안정 구동. 산업 현장 및 대형 시설용.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181154290101122.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '5000W',
      specFormFactor: '대형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '고효율 설계',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 7,
    },
    {
      id: createId(),
      slug: 'gy-e6000',
      name: '6000W 순수 정현파 인버터',
      nameEn: '6000W Pure Sine Wave Inverter',
      modelNo: 'GY-E6000',
      categoryId: catMap['power-inverter']!,
      description:
        '6000W 최고출력 순정사인파 인버터. 절연 PCB 설계로 안전성 극대화. 산업용 최상위 모델.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181202190194453.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '6000W',
      specFormFactor: '대형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        'LCD 디스플레이',
        '무선 리모컨',
        '절연 PCB 설계',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 8,
    },

    // 2. 탈착형 LCD 인버터 (4)
    {
      id: createId(),
      slug: 'gy-lcd1000',
      name: '1000W 탈착형 LCD 인버터',
      nameEn: '1000W Detachable LCD Inverter',
      modelNo: 'GY-LCD1000',
      categoryId: catMap['lcd-inverter']!,
      description:
        '탈착형 LCD 리모컨이 내장된 1000W 순정사인파 인버터. 실시간 전압/전력 모니터링. 2년 품질보증.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181139060158598.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '탈착형 LCD 디스플레이',
        '순정사인파 출력',
        '스마트 냉각',
        '종합 보호 기능',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 9,
    },
    {
      id: createId(),
      slug: 'gy-lcd1500',
      name: '1500W 탈착형 LCD 인버터',
      nameEn: '1500W Detachable LCD Inverter',
      modelNo: 'GY-LCD1500',
      categoryId: catMap['lcd-inverter']!,
      description:
        '탈착형 LCD 리모컨이 내장된 1500W 순정사인파 인버터. 절연 PCB 설계로 안정성 강화.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181139060158598.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1500W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '탈착형 LCD 디스플레이',
        '순정사인파 출력',
        '절연 PCB 설계',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 10,
    },
    {
      id: createId(),
      slug: 'gy-lcd2000',
      name: '2000W 탈착형 LCD 인버터',
      nameEn: '2000W Detachable LCD Inverter',
      modelNo: 'GY-LCD2000',
      categoryId: catMap['lcd-inverter']!,
      description:
        '탈착형 LCD 리모컨이 내장된 2000W 순정사인파 인버터. 고서지 전력 지원, 무선 리모컨 포함.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181128350107182.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '2000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '탈착형 LCD 디스플레이',
        '고서지 전력',
        '무선 리모컨',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 11,
    },
    {
      id: createId(),
      slug: 'gy-lcd3000',
      name: '3000W 탈착형 LCD 인버터',
      nameEn: '3000W Detachable LCD Inverter',
      modelNo: 'GY-LCD3000',
      categoryId: catMap['lcd-inverter']!,
      description:
        '탈착형 LCD 리모컨이 내장된 3000W 순정사인파 인버터. 지능형 냉각 시스템, 컴팩트 설계.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181128350107182.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '3000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '탈착형 LCD 디스플레이',
        '지능형 냉각',
        '컴팩트 설계',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 12,
    },

    // 3. UPS 인버터 충전기 (4)
    {
      id: createId(),
      slug: 'gy-pc1000w',
      name: '1000W UPS 인버터 충전기',
      nameEn: '1000W UPS Inverter Charger',
      modelNo: 'GY-PC1000W',
      categoryId: catMap['ups-inverter']!,
      description:
        '인버터+충전기+UPS 3in1 시스템. 30A 고속 충전기 내장. LiFePO4 배터리 호환. 전환시간 8.4ms 이하.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181519160184600.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '3in1 인버터/충전기/UPS',
        '30A 고속 충전',
        'LiFePO4 호환',
        '전환시간 <8.4ms',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 13,
    },
    {
      id: createId(),
      slug: 'gy-pc1500w',
      name: '1500W UPS 인버터 충전기',
      nameEn: '1500W UPS Inverter Charger',
      modelNo: 'GY-PC1500W',
      categoryId: catMap['ups-inverter']!,
      description:
        '1500W UPS 인버터 충전기. 3단계 충전, 탈착형 LCD. 종합 보호 기능 탑재.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181519160184600.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '1500W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '3단계 스마트 충전',
        '탈착형 LCD',
        '종합 보호 기능',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 14,
    },
    {
      id: createId(),
      slug: 'gy-pc2000w',
      name: '2000W UPS 인버터 충전기',
      nameEn: '2000W UPS Inverter Charger',
      modelNo: 'GY-PC2000W',
      categoryId: catMap['ups-inverter']!,
      description:
        '2000W 순정사인파 UPS 인버터 충전기. 스마트 배터리 충전기, UPS 자동 전환 기능.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181457180141808.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '2000W',
      specFormFactor: '표준형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '순정사인파 출력',
        '스마트 배터리 충전',
        'UPS 자동 전환',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 15,
    },
    {
      id: createId(),
      slug: 'gy-pc3000w',
      name: '3000W UPS 인버터 충전기',
      nameEn: '3000W UPS Inverter Charger',
      modelNo: 'GY-PC3000W',
      categoryId: catMap['ups-inverter']!,
      description:
        '3000W 최고출력 UPS 인버터 충전기. 내장 배터리 충전기, 탈착형 LCD, 절연 PCB 설계.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/18/202512181457180141808.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '3000W',
      specFormFactor: '대형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '내장 배터리 충전기',
        '탈착형 LCD',
        '절연 PCB 설계',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 16,
    },

    // 4. 하이브리드 인버터 (2)
    {
      id: createId(),
      slug: 'vol-max-82kw',
      name: 'VOL-MAX 8.2kW 하이브리드 인버터',
      nameEn: 'VOL-MAX 8.2kW Hybrid Inverter',
      modelNo: 'VOL-MAX-82kW',
      categoryId: catMap['hybrid-inverter']!,
      description:
        '8.2kW 하이브리드 인버터. 최대 160A 충전 전류, 태양광 호환. MPPT 광범위 입력 범위 지원.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/07/02/202407021001130110341.jpg',
      specInputVoltage: 'DC 48V / PV 90~450V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '8200W',
      specFormFactor: '벽걸이형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        '고충전 전류 160A',
        '태양광 호환',
        'MPPT 충전 컨트롤러',
        '그리드 타이 기능',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 17,
    },
    {
      id: createId(),
      slug: 'vol-max-102kw',
      name: 'VOL-MAX 10.2kW 하이브리드 인버터',
      nameEn: 'VOL-MAX 10.2kW Hybrid Inverter',
      modelNo: 'VOL-MAX-102kW',
      categoryId: catMap['hybrid-inverter']!,
      description:
        '10.2kW 최고출력 하이브리드 인버터. AC 최대 충전 140A, 광범위 MPPT 입력 범위. 대형 주택/상업용.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/07/02/202407021001130110341.jpg',
      specInputVoltage: 'DC 48V / PV 90~450V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '10200W',
      specFormFactor: '벽걸이형',
      certifications: 'CE, ROHS, ISO9001',
      features: JSON.stringify([
        'AC 충전 최대 140A',
        '광범위 MPPT',
        '그리드 타이',
        '스마트 모니터링',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 18,
    },

    // 5. 인버터 PCBA (8)
    {
      id: createId(),
      slug: 'pcba-500w',
      name: '500W 인버터 PCBA',
      nameEn: '500W Inverter PCBA',
      modelNo: 'PCBA-500W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '500W 인버터 PCBA 모듈. 소형 경량 설계로 DIY 및 맞춤형 제품에 적합. 순정사인파 출력.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171554240123908.jpg',
      specInputVoltage: 'DC 12V/24V',
      specOutputVoltage: 'AC 220V/230V/240V',
      specPowerW: '500W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '소형 경량',
        '순정사인파 출력',
        'OEM 맞춤 제작',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 19,
    },
    {
      id: createId(),
      slug: 'pcba-1000w',
      name: '1000W 인버터 PCBA',
      nameEn: '1000W Inverter PCBA',
      modelNo: 'PCBA-1000W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '1000W 인버터 PCBA 모듈. OEM/ODM 제조사를 위한 핵심 전력변환 보드.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 120V/220V',
      specPowerW: '1000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '소형 경량 설계',
        'OEM 맞춤 제작',
        '고효율 설계',
        'CE/RoHS 인증',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 20,
    },
    {
      id: createId(),
      slug: 'pcba-1500w',
      name: '1500W 인버터 PCBA',
      nameEn: '1500W Inverter PCBA',
      modelNo: 'PCBA-1500W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '1500W 인버터 PCBA 모듈. 다양한 입력 전압 지원. OEM/ODM 맞춤 설계 가능.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 120V/220V',
      specPowerW: '1500W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['다전압 입력 지원', 'OEM/ODM 맞춤', '고효율']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 21,
    },
    {
      id: createId(),
      slug: 'pcba-2000w',
      name: '2000W 인버터 PCBA',
      nameEn: '2000W Inverter PCBA',
      modelNo: 'PCBA-2000W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '2000W 인버터 PCBA 모듈. 중출력 OEM/ODM 제조에 적합. 고효율 전력 변환.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 120V/220V',
      specPowerW: '2000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['중출력 설계', '고효율 전력 변환', 'OEM 맞춤']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 22,
    },
    {
      id: createId(),
      slug: 'pcba-3000w',
      name: '3000W 인버터 PCBA',
      nameEn: '3000W Inverter PCBA',
      modelNo: 'PCBA-3000W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '3000W 인버터 PCBA 모듈. 고출력 산업용 응용에 적합. 안정적인 전력 변환.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 120V/220V',
      specPowerW: '3000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '고출력 설계',
        '안정적 전력 변환',
        '산업용 응용',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 23,
    },
    {
      id: createId(),
      slug: 'pcba-4000w',
      name: '4000W 인버터 PCBA',
      nameEn: '4000W Inverter PCBA',
      modelNo: 'PCBA-4000W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '4000W 인버터 PCBA 모듈. 24V/48V 입력 전용. 대형 시스템용 핵심 보드.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '4000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['24V/48V 전용', '대형 시스템용', '고효율']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 24,
    },
    {
      id: createId(),
      slug: 'pcba-5000w',
      name: '5000W 인버터 PCBA',
      nameEn: '5000W Inverter PCBA',
      modelNo: 'PCBA-5000W',
      categoryId: catMap['inverter-pcba']!,
      description: '5000W 인버터 PCBA 모듈. 초고출력 산업용 응용. 견고한 설계.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '5000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['초고출력 설계', '산업용 응용', '견고한 설계']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 25,
    },
    {
      id: createId(),
      slug: 'pcba-6000w',
      name: '6000W 인버터 PCBA',
      nameEn: '6000W Inverter PCBA',
      modelNo: 'PCBA-6000W',
      categoryId: catMap['inverter-pcba']!,
      description:
        '6000W 최고출력 인버터 PCBA 모듈. 산업용 최상위 모델. 절연 설계로 안전성 보장.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171614180120970.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '6000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '최고출력 6000W',
        '절연 설계',
        '산업용 최상위',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 26,
    },

    // 6. UPS 인버터 PCBA (7)
    {
      id: createId(),
      slug: 'ups-pcba-1000w',
      name: '1000W UPS 인버터 PCBA',
      nameEn: '1000W UPS Inverter PCBA',
      modelNo: 'UPS-1000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '1000W 양방향 UPS 인버터 PCBA. 충전+인버터+UPS 기능 통합. LiFePO4 호환.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171827430128444.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '1000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['양방향 설계', 'UPS 기능', 'LiFePO4 호환']),
      isFeatured: true,
      isPublished: true,
      sortOrder: 27,
    },
    {
      id: createId(),
      slug: 'ups-pcba-1500w',
      name: '1500W UPS 인버터 PCBA',
      nameEn: '1500W UPS Inverter PCBA',
      modelNo: 'UPS-1500W',
      categoryId: catMap['ups-pcba']!,
      description:
        '1500W 양방향 UPS 인버터 PCBA. 고속 전환으로 무중단 전원 보장.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171827430128444.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '1500W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['양방향 설계', '고속 전환', '무중단 전원']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 28,
    },
    {
      id: createId(),
      slug: 'ups-pcba-2000w',
      name: '2000W UPS 인버터 PCBA',
      nameEn: '2000W UPS Inverter PCBA',
      modelNo: 'UPS-2000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '2000W 양방향 UPS 인버터 PCBA. 스마트 충전 관리. OEM/ODM 맞춤 가능.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171827430128444.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '2000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['양방향 설계', '스마트 충전', 'OEM/ODM 가능']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 29,
    },
    {
      id: createId(),
      slug: 'ups-pcba-3000w',
      name: '3000W UPS 인버터 PCBA',
      nameEn: '3000W UPS Inverter PCBA',
      modelNo: 'UPS-3000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '3000W 양방향 UPS 인버터 PCBA. 고출력 산업용 응용. 안정적인 UPS 전환.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171838570158704.jpg',
      specInputVoltage: 'DC 12V/24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '3000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '양방향 설계',
        '고출력 산업용',
        '안정적 UPS 전환',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 30,
    },
    {
      id: createId(),
      slug: 'ups-pcba-4000w',
      name: '4000W UPS 인버터 PCBA',
      nameEn: '4000W UPS Inverter PCBA',
      modelNo: 'UPS-4000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '4000W 양방향 UPS 인버터 PCBA. 대형 시스템용. 24V/48V 입력 전용.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171838570158704.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '4000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        '양방향 설계',
        '24V/48V 전용',
        '대형 시스템용',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 31,
    },
    {
      id: createId(),
      slug: 'ups-pcba-5000w',
      name: '5000W UPS 인버터 PCBA',
      nameEn: '5000W UPS Inverter PCBA',
      modelNo: 'UPS-5000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '5000W 양방향 UPS 인버터 PCBA. 초고출력 산업용. 피크 10000W 서지 지원.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171838570158704.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '5000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['양방향 설계', '피크 10000W', '초고출력']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 32,
    },
    {
      id: createId(),
      slug: 'ups-pcba-6000w',
      name: '6000W UPS 인버터 PCBA',
      nameEn: '6000W UPS Inverter PCBA',
      modelNo: 'UPS-6000W',
      categoryId: catMap['ups-pcba']!,
      description:
        '6000W 최고출력 양방향 UPS 인버터 PCBA. 피크 12000W. 산업용 최상위 모델.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2025/12/17/202512171838570158704.jpg',
      specInputVoltage: 'DC 24V/48V',
      specOutputVoltage: 'AC 220V',
      specPowerW: '6000W',
      specFormFactor: 'PCBA 모듈',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['양방향 설계', '피크 12000W', '산업용 최상위']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 33,
    },

    // 7. 마이크로 인버터 (9)
    {
      id: createId(),
      slug: 'micro-350w',
      name: '350W 태양광 마이크로 인버터',
      nameEn: '350W Solar Micro Inverter',
      modelNo: 'MI-350W',
      categoryId: catMap['micro-inverter']!,
      description:
        '350W 태양광 마이크로 인버터. IP65 방수, 433MHz 무선 통신. 주택용 소형 태양광 패널에 최적.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '350W',
      specFormFactor: '소형 방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        'MPPT 효율 99.9%',
        'IP65 방수',
        '433MHz 무선 통신',
        '순정사인파 출력',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 34,
    },
    {
      id: createId(),
      slug: 'micro-400w',
      name: '400W 태양광 마이크로 인버터',
      nameEn: '400W Solar Micro Inverter',
      modelNo: 'MI-400W',
      categoryId: catMap['micro-inverter']!,
      description:
        '400W 태양광 마이크로 인버터. MPPT 99.9% 효율. 컴팩트한 설계로 설치 간편.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '400W',
      specFormFactor: '소형 방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['MPPT 효율 99.9%', 'IP65 방수', '컴팩트 설계']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 35,
    },
    {
      id: createId(),
      slug: 'micro-600w',
      name: '600W 태양광 마이크로 인버터',
      nameEn: '600W Solar Micro Inverter',
      modelNo: 'MI-600W',
      categoryId: catMap['micro-inverter']!,
      description:
        '600W 태양광 마이크로 인버터. 중출력 주택용 태양광 시스템에 적합.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '600W',
      specFormFactor: '소형 방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['MPPT 효율 99.9%', 'IP65 방수', '그리드 타이']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 36,
    },
    {
      id: createId(),
      slug: 'micro-700w',
      name: '700W 태양광 마이크로 인버터',
      nameEn: '700W Solar Micro Inverter',
      modelNo: 'MI-700W',
      categoryId: catMap['micro-inverter']!,
      description:
        '700W 태양광 마이크로 인버터. 광범위 출력 전압 지원. 안정적인 그리드 타이 운전.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 80~160V / 180~280V',
      specPowerW: '700W',
      specFormFactor: '소형 방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        'MPPT 효율 99%',
        'IP65 방수',
        '광범위 출력 전압',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 37,
    },
    {
      id: createId(),
      slug: 'micro-800w',
      name: '800W 태양광 마이크로 인버터',
      nameEn: '800W Solar Micro Inverter',
      modelNo: 'MI-800W',
      categoryId: catMap['micro-inverter']!,
      description:
        '800W 태양광 마이크로 인버터. 중급 주택용 태양광 시스템에 적합.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '800W',
      specFormFactor: '소형 방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        'MPPT 효율 99%',
        'IP65 방수',
        '순정사인파 출력',
      ]),
      isFeatured: false,
      isPublished: true,
      sortOrder: 38,
    },
    {
      id: createId(),
      slug: 'micro-1200w',
      name: '1200W 태양광 마이크로 인버터',
      nameEn: '1200W Solar Micro Inverter',
      modelNo: 'MI-1200W',
      categoryId: catMap['micro-inverter']!,
      description:
        '1200W 태양광 마이크로 인버터. 다중 패널 연결 가능. 고효율 MPPT 내장.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '1200W',
      specFormFactor: '방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify([
        'MPPT 효율 99%',
        'IP65 방수',
        '다중 패널 연결',
      ]),
      isFeatured: true,
      isPublished: true,
      sortOrder: 39,
    },
    {
      id: createId(),
      slug: 'micro-1400w',
      name: '1400W 태양광 마이크로 인버터',
      nameEn: '1400W Solar Micro Inverter',
      modelNo: 'MI-1400W',
      categoryId: catMap['micro-inverter']!,
      description:
        '1400W 태양광 마이크로 인버터. 중대형 주택용. -20℃~50℃ 동작 온도.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '1400W',
      specFormFactor: '방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['MPPT 효율 99%', 'IP65 방수', '-20℃~50℃ 동작']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 40,
    },
    {
      id: createId(),
      slug: 'micro-1600w',
      name: '1600W 태양광 마이크로 인버터',
      nameEn: '1600W Solar Micro Inverter',
      modelNo: 'MI-1600W',
      categoryId: catMap['micro-inverter']!,
      description:
        '1600W 태양광 마이크로 인버터. 대형 주택용 태양광 시스템에 적합.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '1600W',
      specFormFactor: '방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['MPPT 효율 99%', 'IP65 방수', '그리드 타이']),
      isFeatured: false,
      isPublished: true,
      sortOrder: 41,
    },
    {
      id: createId(),
      slug: 'micro-2000w',
      name: '2000W 태양광 마이크로 인버터',
      nameEn: '2000W Solar Micro Inverter',
      modelNo: 'MI-2000W',
      categoryId: catMap['micro-inverter']!,
      description:
        '2000W 최고출력 태양광 마이크로 인버터. 상업용 소규모 태양광 시스템에 적합.',
      imageUrl:
        'https://cdn.cloudbf.com/files/208/img/2024/03/21/202403211436180108915.jpg',
      specInputVoltage: 'DC 22~50V',
      specOutputVoltage: 'AC 120V/230V',
      specPowerW: '2000W',
      specFormFactor: '방수형',
      certifications: 'CE, ROHS',
      features: JSON.stringify(['MPPT 효율 99%', 'IP65 방수', '상업용 가능']),
      isFeatured: true,
      isPublished: true,
      sortOrder: 42,
    },
  ];

  await db.insert(products).values(prods).onConflictDoNothing();
  console.log('Products seeded:', prods.length);
  console.log('Seed complete!');
}

seed().catch(console.error);
